apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - name: broker
    port: 9092
  selector:
    app: {{ include "kafka.name" . | quote }}
    release: {{ .Release.Name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}-external
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: LoadBalancer
  ports:
  - name: broker
    port: 9093
  selector:
    app: {{ include "kafka.name" . | quote }}
    release: {{ .Release.Name | quote }}
  {{- if .Values.loadBalancerSourceRangesEnabled }}
  loadBalancerSourceRanges:
{{ toYaml .Values.loadBalancerSourceRanges | indent 2 }}
  {{- end -}}
